HAProxy 2.0.29
iusrepo/haproxy20 pull request #18
Opened 2022-05-27 13:33 UTC by chipitsine

2022-05-27 16:21 UTC, jeffsheltren requested changes
Thanks for this!

Please add a matching changelog entry in the `%changelog` section of the spec and this should be good to go.

2022-05-27 18:38 UTC, jeffsheltren approved these changes

2022-05-27 18:40 UTC, merged

2022-05-27 19:06 UTC, jeffsheltren commented
2.0.29-1.el7.ius has been pushed to IUS testing. I'll get it pushed to stable next week.

2022-05-28 04:01 UTC, chipitsine commented
by the way, how it works ? people push manually ?

I will appreciaste some doc (I could not find one)